// Master multi-tone template system database with real signature dynamic inputs
const templates = {
    intern_firealarm: {
        formal: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Application for Fire Alarm Systems Internship - ${name}\n\nHi ${rec},\n\nI am writing to express my strong interest in a technical internship opportunity with ${comp}. I am highly drawn to your company's work in smart building safety and circuit schematic validation regarding ${ctx}.\n\nI have been studying layout compliance rules to ensure optimized system architecture. ${link ? `You can review a copy of my technical schematics tracker and system layout studies directly here: ${link}\n\n` : ''}\n\nI have my availability open this week—would it be alright if I sent over a quick project blueprint demonstrating how I approach building-safety design calculations to see if it aligns with your current team needs?\n\nBest regards,\n${name}${phone ? `\n📞 Phone: ${phone}` : ''}${linkedin ? `\n🔗 LinkedIn: ${linkedin}` : ''}`,
        creative: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Supercharging Fire Safety at ${comp}! 🔥\n\nHi ${rec},\n\nI've been following ${comp} and absolutely love how you're using cutting-edge engineering to protect buildings! I’m looking for a hands-on systems internship where I can dive headfirst into circuit schematics and workflows for ${ctx}.\n\nI've been teaching myself system design guidelines to build efficient layouts. ${link ? `Check out my live dashboard containing my interactive layout mockups here: ${link}\n\n` : ''}\n\nCan we jump on a quick call this Tuesday or Thursday? I'd love to share a 60-second safety blueprint breakdown I drafted specifically for your system structures.\n\nCheers,\n${name}${phone ? `\n📞 Phone: ${phone}` : ''}${linkedin ? `\n🔗 LinkedIn: ${linkedin}` : ''}`,
        casual: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Quick question re: Fire Alarm Internship at ${comp}\n\nHi ${rec},\n\nI'm looking around for an internship dealing with fire alarm systems and safety design, and ${comp} stood out to me as an amazing place to learn—especially your work on ${ctx}.\n\nI've already spent time breaking down electrical circuit regulations and layout blueprints. ${link ? `Here is a link to the engineering folder I've been working on: ${link}\n\n` : ''}\n\nLet me know if your team has 5 minutes to connect this week. I can easily send over a sample circuit draft I put together to show you my workflow!\n\nThanks,\n${name}${phone ? `\n📞 Phone: ${phone}` : ''}${linkedin ? `\n🔗 LinkedIn: ${linkedin}` : ''}`
    },
    intern_dev: {
        formal: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Frontend Developer Internship Application - ${name}\n\nHi ${rec},\n\nI am contacting you regarding a remote frontend developer internship at ${comp}. I closely follow your software standards and aim to contribute clean code to your web apps, particularly your work on ${ctx}.\n\nI am proficient in modern interface architecture and responsive layouts. ${link ? `My live application repository and production source code can be reviewed here: ${link}\n\n` : ''}\n\nI am free for an interview call this week. Would it be alright to send over a 60-second video walkthrough showing a small UI optimization I mapped out for your landing page?\n\nBest regards,\n${name}${phone ? `\n📞 Phone: ${phone}` : ''}${linkedin ? `\n🔗 LinkedIn: ${linkedin}` : ''}`,
        creative: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Building slick, fast UIs for ${comp}! 🚀\n\nHi ${rec},\n\nI absolutely adore ${comp}'s web applications and clean layout structure! I'm a developer looking to break things and rebuild them better during a frontend remote internship, focused on projects like ${ctx}.\n\nI love bringing static designs to life with fully responsive code templates. ${link ? `Take a look at my live web code projects and deployment files here: ${link}\n\n` : ''}\n\nDo you have 2 minutes to check out a quick visual layout audit I did for your homepage? Let me know your availability this week and I'll pass it right over!\n\nBest,\n${name}${phone ? `\n📞 Phone: ${phone}` : ''}${linkedin ? `\n🔗 LinkedIn: ${linkedin}` : ''}`,
        casual: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Frontend dev looking to add value at ${comp}\n\nHi ${rec},\n\nI'm a frontend developer looking for an internship opportunity, and I really like what you guys are building at ${comp}, especially around ${ctx}.\n\nI focus on building clean, modular frontends. ${link ? `You can check out my project work and repository profiles here: ${link}\n\n` : ''}\n\nLet me know if you have any open slots this month—I'd love to drop a quick code sample in your inbox to see if my stack fits what you're looking for.\n\nThanks,\n${name}${phone ? `\n📞 Phone: ${phone}` : ''}${linkedin ? `\n🔗 LinkedIn: ${linkedin}` : ''}`
    },
    intern_uiux: {
        formal: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: UI/UX Design Internship Application - ${name}\n\nHi ${rec},\n\nI am writing to inquire about UI/UX design internship opportunities at ${comp}. I highly respect your emphasis on seamless user experiences, especially on assets like ${ctx}.\n\nI specialize in user research, digital wireframing, and component-driven styles. ${link ? `My complete case studies and interactive design portfolio are fully accessible here: ${link}\n\n` : ''}\n\nI am available for an introductory call any morning this week. May I send over a quick layout wireframe sketch I put together for your user dashboard update?\n\nBest regards,\n${name}${phone ? `\n📞 Phone: ${phone}` : ''}${linkedin ? `\n🔗 LinkedIn: ${linkedin}` : ''}`,
        creative: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Designing beautiful user journeys for ${comp} ✨\n\nHi ${rec},\n\nBad user experience drives me crazy! I am a passionate UI/UX designer eager to pitch in during a creative design internship with ${comp} to help style your projects like ${ctx}.\n\nI turn complex layouts into stunning, effortless high-fidelity flows. ${link ? `See my dynamic Figma prototyping files and boards here: ${link}\n\n` : ''}\n\nLet's connect this week to talk pixels! Drop me a quick reply if it's cool to share a mini design style guide I mocked up for your brand.\n\nWarmly,\n${name}${phone ? `\n📞 Phone: ${phone}` : ''}${linkedin ? `\n🔗 LinkedIn: ${linkedin}` : ''}`,
        casual: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: UI/UX design intern opening at ${comp}?\n\nHi ${rec},\n\nI'm an aspiring UI/UX designer looking for an internship, and I think the design framework you use over at ${comp} for ${ctx} is incredible.\n\nI focus heavily on clean layouts and intuitive grid systems. ${link ? `Here's a direct link to my design profile and wireframes: ${link}\n\n` : ''}\n\nAre you open to a quick chat this week? I have 2 rapid user interface updates I'd love to drop over to get your thoughts on!\n\nBest,\n${name}${phone ? `\n📞 Phone: ${phone}` : ''}${linkedin ? `\n🔗 LinkedIn: ${linkedin}` : ''}`
    },
    intern_writer: {
        formal: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Content Writing Internship Application - ${name}\n\nHi ${rec},\n\nI am submitting my application for a content writing internship with ${comp}. I am confident my writing style aligns directly with your brand messaging goals for ${ctx}.\n\nI specialize in targeted copywriting and educational content structures. ${link ? `You can read my complete catalog of writing samples and case articles here: ${link}\n\n` : ''}\n\nI would love to sync up briefly. To show you what I can bring to the table, I have drafted 3 article outlines that match your upcoming content style—can I pass those over for you to view?\n\nBest regards,\n${name}${phone ? `\n📞 Phone: ${phone}` : ''}${linkedin ? `\n🔗 LinkedIn: ${linkedin}` : ''}`,
        creative: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Copy that clicks! ✍️ Writer Intern App for ${comp}\n\nHi ${rec},\n\nI noticed ${comp} has been producing stellar content for ${ctx}, and I want to write pieces that your audience can't stop sharing! I'm applying for a writing internship.\n\nI love turning complex data into fun, actionable reading material. ${link ? `Check out my creative writing drafts portfolio here: ${link}\n\n` : ''}\n\nI've already outlined 3 explosive topic hooks designed specifically for your brand voice. Let me know your best contact time this week and I'll send them right over!\n\nCheers,\n${name}${phone ? `\n📞 Phone: ${phone}` : ''}${linkedin ? `\n🔗 LinkedIn: ${linkedin}` : ''}`,
        casual: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Content writing intern looking to help out at ${comp}\n\nHi ${rec},\n\nI'm a writer looking for an internship, and I really dig the overall tone and content vibe you guys push out at ${comp} for ${ctx}.\n\nI put together a few drafts tailored exactly to your style guide. ${link ? `Check out my open draft documents link here: ${link}\n\n` : ''}\n\nLet me know if you have a couple of minutes to spare this week—I'd love to share my article outlines to see if they fit what you're planning next!\n\nThanks,\n${name}${phone ? `\n📞 Phone: ${phone}` : ''}${linkedin ? `\n🔗 LinkedIn: ${linkedin}` : ''}`
    },
    intern_video: {
        formal: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Video Editing & Content Creation Internship - ${name}\n\nHi ${rec},\n\nI am applying for a video editing internship with ${comp}. I specialize in post-production pacing adjustments and maintaining viewer retention analytics on projects like ${ctx}.\n\nI am proficient with advanced timeline edits and motion graphics integration. ${link ? `My professional video showreel and editing portfolio is available here: ${link}\n\n` : ''}\n\nI am fully available for a meeting this week. Can I edit one sample short video or social media reel for your team completely free to show you my timeline speed?\n\nBest regards,\n${name}${phone ? `\n📞 Phone: ${phone}` : ''}${linkedin ? `\n🔗 LinkedIn: ${linkedin}` : ''}`,
        creative: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Let's make viral video edits for ${comp}! 🎬🍿\n\nHi ${rec},\n\nHigh-retention editing is a game of frames, and I know exactly how to hook an audience in the first 3 seconds! I'm a video editor pitching for an internship with ${comp} to scale up your ${ctx} video assets.\n\nI specialize in dynamic pacing, sound design, and attention-grabbing social media edits. ${link ? `Check out my editing cut-downs and video showreel link here: ${link}\n\n` : ''}\n\nI'm ready to tackle a test project! Let me know your availability this week and I'll jump on a quick sync to grab a raw clip from you guys.\n\nExcitedly,\n${name}${phone ? `\n📞 Phone: ${phone}` : ''}${linkedin ? `\n🔗 LinkedIn: ${linkedin}` : ''}`,
        casual: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Video editor looking to cut clips for ${comp}\n\nHi ${rec},\n\nI'm a content creator/video editor looking for an internship opportunity. I love the video concepts you guys push out at ${comp}, especially regarding ${ctx}.\n\nI focus on crisp timing and high-impact cuts. ${link ? `Here is a link to my recent work video dashboard: ${link}\n\n` : ''}\n\nIf you have a quick free slot this week, hit me back—I'd love to edit a 30-second teaser for you for free to see if you like my cutting style.\n\nBest,\n${name}${phone ? `\n📞 Phone: ${phone}` : ''}${linkedin ? `\n🔗 LinkedIn: ${linkedin}` : ''}`
    },
    work_delivery: {
        formal: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Project Delivery: ${ctx} Submission\n\nHi ${rec},\n\nI am pleased to deliver the completed project assets for ${ctx} to the team at ${comp}. Everything has been structured in compliance with our agreed criteria.\n\n${link ? `The final secure deliverable files can be downloaded here: ${link}\n\n` : ''}Please let me know if you require any modifications or formal sign-offs. I am available at my direct line below if you wish to review live.\n\nBest regards,\n${name}${phone ? `\n📞 Phone: ${phone}` : ''}${linkedin ? `\n🔗 LinkedIn: ${linkedin}` : ''}`,
        creative: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Fresh out of the oven! 🧑‍🍳 Project assets for ${comp}\n\nHi ${rec},\n\nIt's done! I've finalized the creative assets for ${ctx} and focused completely on making the visuals pop so they match ${comp}'s brand standard.\n\n${link ? `Dive directly into the live project files here: ${link}\n\n` : ''}Take a look through and hit me with your thoughts on our thread so we can launch this thing! Call or text me anytime if you want to jump on a screen-share.\n\nBest,\n${name}${phone ? `\n📞 Phone: ${phone}` : ''}${linkedin ? `\n🔗 LinkedIn: ${linkedin}` : ''}`,
        casual: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Finished up the files for ${ctx}!\n\nHi ${rec},\n\nJust wrapping up the work for ${ctx} over at ${comp}. I've cleaned everything up so it's super easy to navigate.\n\n${link ? `Here is the direct link to the folder: ${link}\n\n` : ''}Check it over when you get a free slot and let me know if it all looks good! You can reach me directly on my cell below if anything needs fixing.\n\nThanks,\n${name}${phone ? `\n📞 Phone: ${phone}` : ''}${linkedin ? `\n🔗 LinkedIn: ${linkedin}` : ''}`
    },
    work_feedback: {
        formal: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Request for Project Review and Feedback - ${ctx}\n\nHi ${rec},\n\nI have assembled the initial design draft for ${ctx} at ${comp}. I would appreciate your formal assessment regarding layout alignment and structural flow.\n\n${link ? `The current asset draft can be accessed here: ${link}\n\n` : ''}Kindly advise on any necessary adjustments required to proceed. I can be reached below if a call is more efficient.\n\nBest regards,\n${name}${phone ? `\n📞 Phone: ${phone}` : ''}${linkedin ? `\n🔗 LinkedIn: ${linkedin}` : ''}`,
        creative: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Critique Time! 🎨 Thoughts on the new ${ctx} build?\n\nHi ${rec},\n\nI've thrown together the fresh design layout patterns for ${ctx}! I want to make sure the aesthetic matches ${comp}'s brand vision completely.\n\n${link ? `Take a look at the design prototype here: ${link}\n\n` : ''}What stands out to you? Does the color palette strike the right mood? Shoot me a text or jump on a call below to brainstorm!\n\nCheers,\n${name}${phone ? `\n📞 Phone: ${phone}` : ''}${linkedin ? `\n🔗 LinkedIn: ${linkedin}` : ''}`,
        casual: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Quick review check on ${ctx}\n\nHi ${rec},\n\nI've got a working draft of the ${ctx} files ready to share with ${comp}.\n\n${link ? `Here is the link to review: ${link}\n\n` : ''}Let me know if you spot anything that feels off or needs changing before I keep going! Give me a shout below if it's easier to talk it out.\n\nThanks,\n${name}${phone ? `\n📞 Phone: ${phone}` : ''}${linkedin ? `\n🔗 LinkedIn: ${linkedin}` : ''}`
    },
    school_extension: {
        formal: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Extension Request: ${ctx} Submission Date\n\nHi ${rec},\n\nI am writing to respectfully request a short extension on the upcoming deadline for ${ctx} at ${comp}. Due to an unforeseen schedule conflict, I want to ensure my work meets your rigorous academic standards.\n\n${link ? `I have uploaded my current working outline here: ${link}\n\n` : ''}Would it be possible to submit the finalized assignment a couple of days later? Thank you for your time and understanding. I can be reached directly below if necessary.\n\nRespectfully,\n${name}${phone ? `\n📞 Contact: ${phone}` : ''}`,
        creative: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Requesting an extra day or two on ${ctx}! 🙏\n\nHi ${rec},\n\nI'm fully deep into crafting something great for our ${ctx} assignment here at ${comp}, but I need just a little more time to polish the final execution and content details!\n\n${link ? `Here is a preview check of where my draft stands right now: ${link}\n\n` : ''}Could I grab a short extension so I can submit this at its absolute best? Thanks a million! Let me know if it's fine via message.\n\nBest regards,\n${name}${phone ? `\n📞 Contact: ${phone}` : ''}`,
        casual: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Quick question about the ${ctx} deadline\n\nHi ${rec},\n\nI'm working through the assignment for ${ctx} for ${comp} right now, but running slightly behind on fine-tuning the last bits.\n\n${link ? `Here's a link to my progress so far: ${link}\n\n` : ''}Is it cool if I hand this in a bit later so I can clean up the errors properly? Let me know if that works!\n\nThanks,\n\nBest,\n${name}${phone ? `\n📞 Contact: ${phone}` : ''}`
    },
    school_leave: {
        formal: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Notice of Absence due to Medical Reasons - ${name}\n\nHi ${rec},\n\nI am writing to formally notify you that I will be unable to attend sessions at ${comp} regarding ${ctx} due to a sudden illness. I intend to review all assigned curriculum material remotely to keep pace.\n\n${link ? `I have uploaded my medical verification file here: ${link}\n\n` : ''}Thank you for updating my attendance records. I will reach out immediately upon my recovery.\n\nSincerely,\n${name}${phone ? `\n📞 Contact: ${phone}` : ''}`,
        creative: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Out of commission today! 🤒 Absence notice for ${ctx}\n\nHi ${rec},\n\nMy immune system went on a sudden strike, so I won't be able to make it to ${comp} for our ${ctx} session today. I'm taking the day to rest up and reset.\n\n${link ? `Medical verification / documentation can be viewed here: ${link}\n\n` : ''}I'll follow up with classmates to copy the notes and stay on track. Text me below if there's an announcement I missed!\n\nBest regards,\n${name}${phone ? `\n📞 Contact: ${phone}` : ''}`,
        casual: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Out sick today - ${name}\n\nHi ${rec},\n\nI've caught a bug and won't be able to make it in to ${comp} for ${ctx} today. I'm going to rest up to get over it quickly.\n\n${link ? `Here is a link to my notes/details: ${link}\n\n` : ''}Let me know if there's any critical assignment I should check out from home! Ping me below anytime.\n\nThanks,\n\nBest,\n${name}${phone ? `\n📞 Contact: ${phone}` : ''}`
    },
    everyday_followup: {
        formal: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Follow-up regarding ${ctx} Status\n\nHi ${rec},\n\nI am writing to follow up on our last discussion at ${comp} regarding ${ctx}. I want to ensure you have all documentation required from my side to advance this file.\n\n${link ? `For quick reference, our asset tracker dashboard is located here: ${link}\n\n` : ''}I await your guidance on any subsequent milestones, and I am fully open at my line below for a check-in sync.\n\nBest regards,\n${name}${phone ? `\n📞 Phone: ${phone}` : ''}${linkedin ? `\n🔗 LinkedIn: ${linkedin}` : ''}`,
        creative: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Bumping this up! ⚡ Quick pulse check on ${ctx}\n\nHi ${rec},\n\nI hope your week is rolling along smoothly! Just popping into your inbox to see how the timelines are looking for ${ctx} over at ${comp}.\n\n${link ? `You can check the updated files repository right here: ${link}\n\n` : ''}Let me know if your team needs any extra brainstorm sessions to push this forward! Drop me a quick message anytime.\n\nBest,\n${name}${phone ? `\n📞 Phone: ${phone}` : ''}${linkedin ? `\n🔗 LinkedIn: ${linkedin}` : ''}`,
        casual: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Quick follow-up on ${ctx}\n\nHi ${rec},\n\nJust bumping this up to see if you had any updates or thoughts about ${ctx} from the ${comp} side.\n\n${link ? `Here is the link to our thread file: ${link}\n\n` : ''}Let me know if you need anything else from my end to move forward! Call me up if it's easier.\n\nThanks,\n${name}${phone ? `\n📞 Phone: ${phone}` : ''}${linkedin ? `\n🔗 LinkedIn: ${linkedin}` : ''}`
    },
    everyday_thankyou: {
        formal: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Thank You for Your Time - ${ctx}\n\nHi ${rec},\n\nThank you very much for taking the time to meet with me regarding ${ctx}. Our discussion reinforced my respect for ${comp}'s operational framework.\n\n${link ? `As discussed, I have linked the extra materials we discussed here: ${link}\n\n` : ''}I look forward to our future professional correspondences and can be contacted directly at the number below.\n\nBest regards,\n${name}${phone ? `\n📞 Phone: ${phone}` : ''}${linkedin ? `\n🔗 LinkedIn: ${linkedin}` : ''}`,
        creative: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Loved our conversation about ${ctx}! 🙌\n\nHi ${rec},\n\nThank you so much for the fantastic chat about ${ctx}! Your perspective on workflows completely sparked a bunch of cool design ideas for what you guys do at ${comp}.\n\n${link ? `I've uploaded those extra references we talked about here: ${link}\n\n` : ''}Can't wait to see where this project goes next. Let's talk soon—call or message me anytime below!\n\nCheers,\n${name}${phone ? `\n📞 Phone: ${phone}` : ''}${linkedin ? `\n🔗 LinkedIn: ${linkedin}` : ''}`,
        casual: (name, rec, comp, ctx, link, phone, linkedin) => `Subject: Great meeting you! Thank you\n\nHi ${rec},\n\nJust wanted to send a quick thank you note for taking the time to chat about ${ctx} at ${comp} today. It was super helpful to get your insights.\n\n${link ? `Here is that link I mentioned during our conversation: ${link}\n\n` : ''}Let's stay in touch as things develop! You can reach me here directly.\n\nBest,\n${name}${phone ? `\n📞 Phone: ${phone}` : ''}${linkedin ? `\n🔗 LinkedIn: ${linkedin}` : ''}`
    }
};

// Grabbing the HTML elements
const generateBtn = document.getElementById('generateBtn');
const copyBtn = document.getElementById('copyBtn');
const emailOutput = document.getElementById('emailOutput');

// What happens when you click "Generate Email"
generateBtn.addEventListener('click', () => {
    const yourName = document.getElementById('yourName').value.trim() || "[Your Name]";
    const prefix = document.getElementById('titlePrefix').value;
    let recipientInput = document.getElementById('recipientName').value.trim();
    
    if (!recipientInput) {
        recipientInput = "Team";
    }

    const fullRecipient = prefix + recipientInput;
    const company = document.getElementById('companyName').value.trim() || "[Company/School Name]";
    const context = document.getElementById('contextName').value.trim() || "[Subject Detail]";
    const link = document.getElementById('projectLink').value.trim();
    const phone = document.getElementById('userPhone').value.trim();
    const linkedin = document.getElementById('userLinkedin').value.trim();
    const role = document.getElementById('roleType').value;
    const tone = document.getElementById('emailTone').value;

    // Safety Check
    if (!templates[role] || !templates[role][tone]) {
        alert(`Error: Dataset mismatch for ${role} in ${tone} mode.`);
        return;
    }

    // Process variables into template output
    const generatedEmail = templates[role][tone](yourName, fullRecipient, company, context, link, phone, linkedin);
    
    // Render text to screen inside the container
    emailOutput.innerText = generatedEmail;
});

// What happens when you click "Copy to Clipboard"
copyBtn.addEventListener('click', () => {
    const textToCopy = emailOutput.innerText;
    if (textToCopy.includes("Fill out the boxes above")) {
        alert("Please generate an email first! 😊");
        return;
    }
    navigator.clipboard.writeText(textToCopy).then(() => {
        alert("Email template copied to clipboard! 🚀");
    });
});
